class_name FieldMoveResource
extends Resource

## A FIELD MOVE (docs/design/DECISIONS.md #41 / #71 / #92): an OUT-OF-COMBAT ability used on the
## overworld to open the world, HM-style -- the tree-felling move a chief teaches (Nyra, #40), later
## the power to cross the sea (the Beach Village chief, #43). Pure data: which story flag makes it
## TEACHABLE, and WHO CAN LEARN it -- specific creature [member species] (a member's current form or
## its evolution line) and specific [member humans] (character ids, e.g. the hero's unit). An
## obstacle on the map ([FieldObstacleEntity]) names the move it needs by [member id].
##
## LEARNED, not carried (#92): a party member LEARNS the move ([member StoryPartyMember.field_moves],
## saved) -- a chief teaches it ([TeachFieldMoveCommand]) to one eligible member the player picks.
## The move is USABLE when a FIELDABLE party member has learned it. Every rule here is a pure
## function of a [StoryState], so it is unit-testable and the overworld never decides it twice.
##
## Shipped moves live at [constant DIR]<id>.tres (generated by build_story_content.gd).

const DIR := "res://game/overworld/content/field_moves/"

## [method status] values.
const STATUS_LOCKED := "locked"
const STATUS_NO_USER := "no_user"
const STATUS_READY := "ready"

## Stable id (also the key a member's [member StoryPartyMember.field_moves] stores -- never rename
## once shipped).
@export var id: StringName = &""
## What the prompt calls it ("Use <display_name>?").
@export var display_name: String = ""
## The story flag that makes the move TEACHABLE (a chief's win sets it). Blank = always.
@export var unlock_flag: String = ""
## Creature species (CharacterLibrary ids) that can LEARN it -- a member's current form OR its
## evolution line.
@export var species: Array[StringName] = []
## HUMANS (CharacterLibrary ids of human units, e.g. the hero's "wren") that can LEARN it
## (#71: "possibly the hero as well").
@export var humans: Array[StringName] = []
## Shown when the move is not teachable yet and nobody knows it (one line, nothing forced). {move}.
@export_multiline var locked_hint: String = ""
## Shown when the move can be taught but no fit party member has learned it. {move} = the name.
@export_multiline var no_user_hint: String = ""
## The Yes / No question. {move} = the name.
@export_multiline var prompt_text: String = "Use {move}?"
## The toast after it is used. {user} = who used it, {move} = the name.
@export var used_text: String = "{user} used {move}!"
## The toast when a member learns it. {user} = who learned it, {move} = the name.
@export var learned_text: String = "{user} learned {move}!"


## The shipped move [param move_id] (trusted content), or null.
static func load_by_id(move_id: String) -> FieldMoveResource:
	if move_id.strip_edges().is_empty():
		return null
	var path: String = path_for(move_id)
	if not ResourceLoader.exists(path):
		return null
	return load(path) as FieldMoveResource


static func path_for(move_id: String) -> String:
	return "%s%s.tres" % [DIR, move_id]


## The move can be taught (its unlock flag is set, or it needs none).
func is_unlocked(state: StoryState) -> bool:
	if unlock_flag.strip_edges().is_empty():
		return true
	return state != null and state.has_flag(unlock_flag)


## Can a creature of species [param character_id] (or of line [param line]) learn the move?
func species_can_learn(character_id: String, line: String = "") -> bool:
	return _listed(species, character_id, line)


## Can the human [param character_id] (or of line [param line]) learn the move?
func human_can_learn(character_id: String, line: String = "") -> bool:
	return _listed(humans, character_id, line)


static func _listed(ids: Array[StringName], character_id: String, line: String) -> bool:
	for s in ids:
		var sid: String = String(s)
		if sid == character_id or (not line.is_empty() and sid == line):
			return true
	return false


## Can party member [param m] learn the move (a listed human, or a creature of a listed species)?
func can_learn(m: StoryPartyMember) -> bool:
	if m == null:
		return false
	if m.is_human():
		return human_can_learn(m.character_id, m.line)
	return species_can_learn(m.character_id, m.line)


## The party members (in party order, hero first as the party keeps him) who could learn it now:
## eligible and not knowing it yet. Wounded members count (learning needs no fight in them).
func teachable_members(state: StoryState) -> Array[StoryPartyMember]:
	var out: Array[StoryPartyMember] = []
	if state == null:
		return out
	for m in state.party:
		if not m.knows_field_move(String(id)) and can_learn(m):
			out.append(m)
	return out


## Every party member who has learned it (fit or not).
func known_by(state: StoryState) -> Array[StoryPartyMember]:
	var out: Array[StoryPartyMember] = []
	if state == null:
		return out
	for m in state.party:
		if m.knows_field_move(String(id)):
			out.append(m)
	return out


## The FIELDABLE party members (in party order) who have learned it -- the ones who can use it.
## A knocked-out member cannot (HM-style: the one who does the work has to be standing); the fallen
## are not in the party.
func capable_members(state: StoryState) -> Array[StoryPartyMember]:
	var out: Array[StoryPartyMember] = []
	if state == null:
		return out
	for m in state.healthy_members():
		if m.knows_field_move(String(id)):
			out.append(m)
	return out


## Someone fit in the party has learned it.
func has_user(state: StoryState) -> bool:
	return not capable_members(state).is_empty()


## [constant STATUS_READY] (a fit member knows it), [constant STATUS_LOCKED] (not teachable yet
## and nobody knows it) or [constant STATUS_NO_USER] (teachable, but no fit member has learned it).
func status(state: StoryState) -> String:
	if has_user(state):
		return STATUS_READY
	if not is_unlocked(state) and known_by(state).is_empty():
		return STATUS_LOCKED
	return STATUS_NO_USER


## Who uses it: the first fit member who knows it, else [param fallback].
func user_name(state: StoryState, fallback: String = "{hero}") -> String:
	var members: Array[StoryPartyMember] = capable_members(state)
	if not members.is_empty():
		return members[0].display_name()
	return fallback


## [param text] with {move} (and {user}) filled in.
func fill(text: String, user: String = "") -> String:
	return text.replace("{move}", display_name).replace("{user}", user)


func validate(issues: Array[String]) -> void:
	var where: String = "field move '%s'" % String(id)
	if String(id).strip_edges().is_empty():
		issues.append("a field move has no id")
	if display_name.strip_edges().is_empty():
		issues.append("%s: no display name" % where)
	if species.is_empty() and humans.is_empty():
		issues.append("%s: nobody can ever learn it (no species, no humans)" % where)
	for s in species:
		if CharacterLibrary.get_character(s) == null:
			issues.append("%s: species '%s' does not exist" % [where, s])
	for h in humans:
		var c: CharacterResource = CharacterLibrary.get_character(h)
		if c == null:
			issues.append("%s: human '%s' does not exist" % [where, h])
		elif not c.is_human():
			issues.append("%s: '%s' is listed as a human but is a creature" % [where, h])
	if locked_hint.strip_edges().is_empty() or no_user_hint.strip_edges().is_empty():
		issues.append("%s: needs a locked hint and a no-user hint" % where)
