class_name FieldMoveResource
extends Resource

## A FIELD MOVE (docs/design/DECISIONS.md #41 / #71): an OUT-OF-COMBAT ability used on the overworld
## to open the world, HM-style -- the tree-felling move a chief teaches (Nyra, #40), later the power
## to cross the sea (the Beach Village chief, #43). Pure data: which story flag UNLOCKS it, which
## party SPECIES can use it, and whether the HERO can use it himself (#71: "possibly the hero as
## well"). An obstacle on the map ([FieldObstacleEntity]) names the move it needs by [member id].
##
## A move is USABLE when it is unlocked AND someone can use it: the hero (when
## [member hero_can_use]) or a fieldable party member whose species (its current form or its
## evolution line) is in [member species]. Every rule here is a pure function of a [StoryState], so
## it is unit-testable and the overworld never decides it twice.
##
## Shipped moves live at [constant DIR]<id>.tres (generated by build_story_content.gd).

const DIR := "res://game/overworld/content/field_moves/"

## [method status] values.
const STATUS_LOCKED := "locked"
const STATUS_NO_USER := "no_user"
const STATUS_READY := "ready"

## Stable id (a save never stores it: the unlock is a flag, a cleared obstacle is a flag).
@export var id: StringName = &""
## What the prompt calls it ("Use <display_name>?").
@export var display_name: String = ""
## The story flag that grants the move (a chief's win sets it). Blank = always unlocked.
@export var unlock_flag: String = ""
## Species (CharacterLibrary ids) that can use it -- a member's current form OR its evolution line.
@export var species: Array[StringName] = []
## The hero can use it himself, with no creature (DECISIONS.md #71).
@export var hero_can_use: bool = false
## Shown when the move is not unlocked yet (one line, no forced dialogue). {move} = the name.
@export_multiline var locked_hint: String = ""
## Shown when the move is unlocked but nobody present can use it. {move} = the name.
@export_multiline var no_user_hint: String = ""
## The Yes / No question. {move} = the name.
@export_multiline var prompt_text: String = "Use {move}?"
## The toast after it is used. {user} = who used it, {move} = the name.
@export var used_text: String = "{user} used {move}!"


## The shipped move [param move_id] (trusted content), or null.
static func load_by_id(move_id: String) -> FieldMoveResource:
	if move_id.strip_edges().is_empty():
		return null
	var path: String = path_for(move_id)
	if not ResourceLoader.exists(path):
		return null
	return load(path) as FieldMoveResource


static func path_for(move_id: String) -> String:
	return "%s%s.tres" % [DIR, move_id]


## The move has been granted (its unlock flag is set, or it needs none).
func is_unlocked(state: StoryState) -> bool:
	if unlock_flag.strip_edges().is_empty():
		return true
	return state != null and state.has_flag(unlock_flag)


## Can a creature of species [param character_id] (or of line [param line]) use the move?
func species_can_use(character_id: String, line: String = "") -> bool:
	for s in species:
		var sid: String = String(s)
		if sid == character_id or (not line.is_empty() and sid == line):
			return true
	return false


## The fieldable party members (in party order) that can use the move. Knocked-out members cannot
## (HM-style: the one who does the work has to be standing); the fallen are not in the party.
func capable_members(state: StoryState) -> Array[StoryPartyMember]:
	var out: Array[StoryPartyMember] = []
	if state == null:
		return out
	for m in state.healthy_members():
		if species_can_use(m.character_id, m.line):
			out.append(m)
	return out


## Someone present can use it (the hero, or a capable member) -- ignoring the unlock.
func has_user(state: StoryState) -> bool:
	return hero_can_use or not capable_members(state).is_empty()


## [constant STATUS_LOCKED] (not granted yet), [constant STATUS_NO_USER] (granted, nobody can use
## it) or [constant STATUS_READY].
func status(state: StoryState) -> String:
	if not is_unlocked(state):
		return STATUS_LOCKED
	if not has_user(state):
		return STATUS_NO_USER
	return STATUS_READY


## Who uses it: the first capable member's name, else the hero ([param hero_name]).
func user_name(state: StoryState, hero_name: String = "{hero}") -> String:
	var members: Array[StoryPartyMember] = capable_members(state)
	if not members.is_empty():
		return members[0].display_name()
	return hero_name


## [param text] with {move} (and {user}) filled in.
func fill(text: String, user: String = "") -> String:
	return text.replace("{move}", display_name).replace("{user}", user)


func validate(issues: Array[String]) -> void:
	var where: String = "field move '%s'" % String(id)
	if String(id).strip_edges().is_empty():
		issues.append("a field move has no id")
	if display_name.strip_edges().is_empty():
		issues.append("%s: no display name" % where)
	if species.is_empty() and not hero_can_use:
		issues.append("%s: nobody can ever use it (no species, hero_can_use off)" % where)
	for s in species:
		if CharacterLibrary.get_character(s) == null:
			issues.append("%s: species '%s' does not exist" % [where, s])
	if locked_hint.strip_edges().is_empty() or no_user_hint.strip_edges().is_empty():
		issues.append("%s: needs a locked hint and a no-user hint" % where)
