class_name WorldLocation
extends Resource

## ONE PLACE ON THE WORLD MAP (docs/STORY_MODE.md "The world map"): a village, a city, a route,
## a dungeon, an island. Held by [WorldAtlas] (game/overworld/content/world.tres, generated by
## build_story_content.gd from the owner's world map). A place is either BUILT -- it has a
## walkable [member area_id] (or several: Oakvale and its ruins share one place) -- or CLOSED:
## on the map, reachable later, its road held shut by [member open_flag] until that chapter is
## built.

enum Status { BUILT, CLOSED }

@export var id: StringName = &""
@export var display_name: String = ""
## "city" / "town" / "village" / "route" / "dungeon" / "special" / "island" / "nation".
@export var kind: String = "village"
## The map region it lies in ([member WorldAtlas.regions] holds their names).
@export var region_id: StringName = &""
## Normalised 0..1 position on the world map image (x right, y down).
@export var map_pos: Vector2 = Vector2.ZERO
@export var status: Status = Status.CLOSED
## The walkable areas of this place (game/overworld/content/areas/<id>/); empty while CLOSED.
@export var area_ids: Array[StringName] = []
## The story flag that opens the road to a CLOSED place ("world.<x>_open"); "" when BUILT.
@export var open_flag: String = ""
## A secret place (the Hidden Thieves Guild): left off the map until [member open_flag] is set.
@export var secret: bool = false
@export_multiline var description: String = ""


func is_built() -> bool:
	return status == Status.BUILT


## Shown on the world map under [param state]'s flags (a secret only once found).
func is_known(state: StoryState) -> bool:
	if not secret:
		return true
	return state != null and not open_flag.is_empty() and state.has_flag(open_flag)


func validate(issues: Array[String]) -> void:
	if String(id).is_empty():
		issues.append("a world location has no id")
	if display_name.is_empty():
		issues.append("%s: no display name" % String(id))
	if map_pos.x < 0.0 or map_pos.x > 1.0 or map_pos.y < 0.0 or map_pos.y > 1.0:
		issues.append("%s: map_pos %s is off the map" % [String(id), str(map_pos)])
	if is_built() and area_ids.is_empty():
		issues.append("%s: built but has no area" % String(id))
	if not is_built() and open_flag.is_empty():
		issues.append("%s: closed but no flag opens it" % String(id))
