class_name WorldAtlas
extends Resource

## THE WORLD MAP AS DATA (docs/STORY_MODE.md "The world map"): every named place on the owner's
## world map ([WorldLocation]s -- built or closed), the regions they lie in, and the roads between
## them. Generated by build_story_content.gd into [constant PATH]; the world map screen and later
## chapters read it instead of hard-coding geography. A road's kind follows the map legend:
## "main" (the gold road), "secondary" (dashed tracks) and "sea" (sailing routes).

const PATH := "res://game/overworld/content/world.tres"
const ROAD_KINDS: Array[String] = ["main", "secondary", "sea"]

@export var world_name: String = ""
## {region_id: display name}.
@export var regions: Dictionary = {}
@export var locations: Array[WorldLocation] = []
## [{"a": StringName, "b": StringName, "kind": "main" | "secondary" | "sea"}] -- undirected.
@export var roads: Array[Dictionary] = []


static func load_default() -> WorldAtlas:
	if not ResourceLoader.exists(PATH):
		return null
	return load(PATH) as WorldAtlas


func location(location_id: String) -> WorldLocation:
	for l in locations:
		if l != null and String(l.id) == location_id:
			return l
	return null


## The place a walkable area belongs to (null for an area the map does not show).
func location_for_area(area_id: String) -> WorldLocation:
	for l in locations:
		if l != null and l.area_ids.has(StringName(area_id)):
			return l
	return null


func location_ids() -> Array[String]:
	var out: Array[String] = []
	for l in locations:
		if l != null:
			out.append(String(l.id))
	return out


## The places one road away from [param location_id] (optionally only roads of [param kind]).
func neighbours(location_id: String, kind: String = "") -> Array[String]:
	var out: Array[String] = []
	for r in roads:
		if not kind.is_empty() and String(r.get("kind", "")) != kind:
			continue
		var a: String = String(r.get("a", ""))
		var b: String = String(r.get("b", ""))
		if a == location_id and not out.has(b):
			out.append(b)
		elif b == location_id and not out.has(a):
			out.append(a)
	return out


func has_road(a: String, b: String) -> bool:
	return neighbours(a).has(b)


## Every built place reachable from [param from_id] over roads through built places only.
func reachable_built(from_id: String) -> Array[String]:
	var seen: Array[String] = [from_id]
	var head: int = 0
	while head < seen.size():
		var cur: String = seen[head]
		head += 1
		for n in neighbours(cur):
			var l := location(n)
			if l != null and l.is_built() and not seen.has(n):
				seen.append(n)
	return seen


func validate() -> Array[String]:
	var issues: Array[String] = []
	var ids: Dictionary = {}
	for l in locations:
		if l == null:
			issues.append("a null location")
			continue
		l.validate(issues)
		if ids.has(l.id):
			issues.append("%s: duplicate location id" % String(l.id))
		ids[l.id] = true
		if not regions.has(l.region_id) and not regions.has(String(l.region_id)):
			issues.append("%s: unknown region '%s'" % [String(l.id), String(l.region_id)])
	for r in roads:
		var a: String = String(r.get("a", ""))
		var b: String = String(r.get("b", ""))
		if location(a) == null or location(b) == null:
			issues.append("road %s - %s names an unknown place" % [a, b])
		if a == b:
			issues.append("road %s loops onto itself" % a)
		if not ROAD_KINDS.has(String(r.get("kind", ""))):
			issues.append("road %s - %s has unknown kind '%s'" % [a, b, String(r.get("kind", ""))])
	return issues
